import React, { useEffect } from 'react';
import { BrowserRouter, Switch, Redirect, Route } from 'react-router-dom';
import { Registration, Map, Users } from './screens';
import './scss/App.scss';

/* eslint-disable react/jsx-props-no-spreading */
const App = () => {
  useEffect(() => {
    if (!JSON.parse(localStorage.getItem('users'))) {
      // Set static dummy data of users
      localStorage.setItem(
        'users',
        JSON.stringify([
          {
            id: 42688679449,
            firstName: 'Roger',
            lastName: 'Orwig',
            birthDate: '04/23/1965',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '09990',
            dateRegistered: 1633262275,
            timeIn: 1633262253,
            timeOut: 1633262309,
            userType: 'Personel',
            gpsDevice: 'GPS-0',
          },

          {
            id: 1187054150583,
            firstName: 'Monte',
            lastName: 'Ebner',
            birthDate: '12/21/1983',
            sex: 'Female',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '09991',
            dateRegistered: 1633262275,
            timeIn: 1633262255,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1191634826332,
            firstName: 'Dan',
            lastName: 'Doran',
            birthDate: '12/03/1961',
            sex: 'Female',
            homeAddress: 'Alfonso XIII',
            contactNumber: '09992',
            dateRegistered: 1633262275,
            timeIn: 1633262220,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-2',
          },

          {
            id: 607379999529,
            firstName: 'Otto',
            lastName: 'Dinkins',
            birthDate: '02/14/1994',
            sex: 'Male',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '09993',
            dateRegistered: 1633262275,
            timeIn: 1633262221,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1412013476705,
            firstName: 'Ike',
            lastName: 'Tandy',
            birthDate: '01/28/1993',
            sex: 'Male',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '09994',
            dateRegistered: 1633262275,
            timeIn: 1633262219,
            timeOut: 1633262336,
            userType: 'Personel',
            gpsDevice: 'GPS-4',
          },

          {
            id: 768921023903,
            firstName: 'Otto',
            lastName: 'Rice',
            birthDate: '04/06/1989',
            sex: 'Male',
            homeAddress: 'F. Antonio 0',
            contactNumber: '09995',
            dateRegistered: 1633262275,
            timeIn: 1633262210,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1274504160469,
            firstName: 'George',
            lastName: 'Ashwoon',
            birthDate: '11/07/1963',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '09996',
            dateRegistered: 1633262275,
            timeIn: 1633262249,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-6',
          },

          {
            id: 120702926263,
            firstName: 'Ben',
            lastName: 'Uflan',
            birthDate: '10/02/2000',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '09997',
            dateRegistered: 1633262275,
            timeIn: 1633262246,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 267638905651,
            firstName: 'Adam',
            lastName: 'Jones',
            birthDate: '09/24/1961',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '09998',
            dateRegistered: 1633262275,
            timeIn: 1633262207,
            timeOut: 1633262328,
            userType: 'Personel',
            gpsDevice: 'GPS-8',
          },

          {
            id: 690616030147,
            firstName: 'Nathan',
            lastName: 'Mills',
            birthDate: '01/13/1987',
            sex: 'Male',
            homeAddress: 'F. Antonio 0',
            contactNumber: '09999',
            dateRegistered: 1633262275,
            timeIn: 1633262195,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 777881086472,
            firstName: 'Joe',
            lastName: 'Ziegler',
            birthDate: '09/02/1961',
            sex: 'Female',
            homeAddress: 'N. Domingo Street',
            contactNumber: '099910',
            dateRegistered: 1633262275,
            timeIn: 1633262246,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-10',
          },

          {
            id: 963684130917,
            firstName: 'Otto',
            lastName: 'Van Zandt',
            birthDate: '05/06/1991',
            sex: 'Female',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099911',
            dateRegistered: 1633262275,
            timeIn: 1633262269,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 186864381568,
            firstName: 'Roger',
            lastName: 'Vail',
            birthDate: '12/22/2001',
            sex: 'Male',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099912',
            dateRegistered: 1633262275,
            timeIn: 1633262267,
            timeOut: 1633262317,
            userType: 'Personel',
            gpsDevice: 'GPS-12',
          },

          {
            id: 915129166783,
            firstName: 'Ty',
            lastName: 'Jurgenson',
            birthDate: '02/09/1970',
            sex: 'Male',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '099913',
            dateRegistered: 1633262275,
            timeIn: 1633262228,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1395706500795,
            firstName: 'Jack',
            lastName: 'Maki',
            birthDate: '12/27/2001',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099914',
            dateRegistered: 1633262275,
            timeIn: 1633262201,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-14',
          },

          {
            id: 1073316953876,
            firstName: 'Paul',
            lastName: 'Aikin',
            birthDate: '12/03/1990',
            sex: 'Female',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099915',
            dateRegistered: 1633262275,
            timeIn: 1633262228,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 595695358286,
            firstName: 'Joe',
            lastName: 'DeLorenzo',
            birthDate: '08/20/1991',
            sex: 'Female',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099916',
            dateRegistered: 1633262275,
            timeIn: 1633262222,
            timeOut: 1633262312,
            userType: 'Personel',
            gpsDevice: 'GPS-16',
          },

          {
            id: 1305200327333,
            firstName: 'Matthew',
            lastName: 'Vanderpoel',
            birthDate: '12/29/1992',
            sex: 'Female',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099917',
            dateRegistered: 1633262275,
            timeIn: 1633262252,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1054988694813,
            firstName: 'Carl',
            lastName: 'Schutz',
            birthDate: '08/29/1967',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099918',
            dateRegistered: 1633262275,
            timeIn: 1633262217,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-18',
          },

          {
            id: 1385821309440,
            firstName: 'Roger',
            lastName: 'Hoffman',
            birthDate: '05/02/1960',
            sex: 'Male',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099919',
            dateRegistered: 1633262275,
            timeIn: 1633262200,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1075083149895,
            firstName: 'Ben',
            lastName: 'Rice',
            birthDate: '12/30/1992',
            sex: 'Female',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099920',
            dateRegistered: 1633262275,
            timeIn: 1633262199,
            timeOut: 1633262308,
            userType: 'Personel',
            gpsDevice: 'GPS-20',
          },

          {
            id: 761712821327,
            firstName: 'Hank',
            lastName: 'Davidson',
            birthDate: '07/14/1964',
            sex: 'Female',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '099921',
            dateRegistered: 1633262275,
            timeIn: 1633262193,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1453284669950,
            firstName: 'Ben',
            lastName: 'Resnick',
            birthDate: '10/30/1988',
            sex: 'Male',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '099922',
            dateRegistered: 1633262275,
            timeIn: 1633262212,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-22',
          },

          {
            id: 1514421741512,
            firstName: 'Edward',
            lastName: 'Celedon',
            birthDate: '12/08/1981',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099923',
            dateRegistered: 1633262275,
            timeIn: 1633262260,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 747973560258,
            firstName: 'Alex',
            lastName: 'Hydinger',
            birthDate: '08/07/1973',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099924',
            dateRegistered: 1633262275,
            timeIn: 1633262272,
            timeOut: 1633262277,
            userType: 'Personel',
            gpsDevice: 'GPS-24',
          },

          {
            id: 819643885832,
            firstName: 'Matthew',
            lastName: 'Boyd',
            birthDate: '04/16/1984',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099925',
            dateRegistered: 1633262275,
            timeIn: 1633262268,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1012381547808,
            firstName: 'Matthew',
            lastName: 'Stahl',
            birthDate: '04/19/1982',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099926',
            dateRegistered: 1633262275,
            timeIn: 1633262240,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-26',
          },

          {
            id: 1322807810856,
            firstName: 'Jack',
            lastName: 'Dinkins',
            birthDate: '01/03/1984',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099927',
            dateRegistered: 1633262275,
            timeIn: 1633262200,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 187788168175,
            firstName: 'Monte',
            lastName: 'Schickowski',
            birthDate: '02/23/1989',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099928',
            dateRegistered: 1633262275,
            timeIn: 1633262219,
            timeOut: 1633262282,
            userType: 'Personel',
            gpsDevice: 'GPS-28',
          },

          {
            id: 1416304736884,
            firstName: 'Nathan',
            lastName: 'Bauer',
            birthDate: '08/12/1998',
            sex: 'Female',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099929',
            dateRegistered: 1633262275,
            timeIn: 1633262258,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1488979262664,
            firstName: 'Roger',
            lastName: 'Aikin',
            birthDate: '03/26/1993',
            sex: 'Female',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099930',
            dateRegistered: 1633262275,
            timeIn: 1633262200,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-30',
          },

          {
            id: 782615304740,
            firstName: 'Joe',
            lastName: 'Solberg',
            birthDate: '06/21/1996',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099931',
            dateRegistered: 1633262275,
            timeIn: 1633262262,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 596543964597,
            firstName: 'Jack',
            lastName: 'Soukup',
            birthDate: '06/23/2000',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099932',
            dateRegistered: 1633262275,
            timeIn: 1633262221,
            timeOut: 1633262356,
            userType: 'Personel',
            gpsDevice: 'GPS-32',
          },

          {
            id: 133036804442,
            firstName: 'Roger',
            lastName: 'Aikin',
            birthDate: '11/29/1976',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099933',
            dateRegistered: 1633262275,
            timeIn: 1633262252,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1190280151666,
            firstName: 'Ike',
            lastName: 'Ashwoon',
            birthDate: '12/07/1985',
            sex: 'Female',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099934',
            dateRegistered: 1633262275,
            timeIn: 1633262261,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-34',
          },

          {
            id: 1334003905106,
            firstName: 'David',
            lastName: 'Lawicki',
            birthDate: '11/11/1994',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099935',
            dateRegistered: 1633262275,
            timeIn: 1633262252,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 491455678769,
            firstName: 'Matthew',
            lastName: 'Uflan',
            birthDate: '08/12/1994',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099936',
            dateRegistered: 1633262275,
            timeIn: 1633262240,
            timeOut: 1633262356,
            userType: 'Personel',
            gpsDevice: 'GPS-36',
          },

          {
            id: 139157925905,
            firstName: 'Carl',
            lastName: 'Yates',
            birthDate: '12/03/1993',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099937',
            dateRegistered: 1633262275,
            timeIn: 1633262211,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1431394693378,
            firstName: 'Alex',
            lastName: 'Johnson',
            birthDate: '05/08/1969',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099938',
            dateRegistered: 1633262275,
            timeIn: 1633262204,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-38',
          },

          {
            id: 1484864472545,
            firstName: 'Thomas',
            lastName: 'Tandy',
            birthDate: '10/07/1981',
            sex: 'Male',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099939',
            dateRegistered: 1633262275,
            timeIn: 1633262249,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1358008363853,
            firstName: 'David',
            lastName: 'Moody',
            birthDate: '01/07/1975',
            sex: 'Female',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099940',
            dateRegistered: 1633262275,
            timeIn: 1633262240,
            timeOut: 1633262345,
            userType: 'Personel',
            gpsDevice: 'GPS-40',
          },

          {
            id: 56895172808,
            firstName: 'Edward',
            lastName: 'Jagtap',
            birthDate: '09/24/1973',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099941',
            dateRegistered: 1633262275,
            timeIn: 1633262231,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1033406199458,
            firstName: 'David',
            lastName: 'Hydinger',
            birthDate: '09/30/1972',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099942',
            dateRegistered: 1633262275,
            timeIn: 1633262201,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-42',
          },

          {
            id: 1481191134159,
            firstName: 'Ben',
            lastName: 'Hesch',
            birthDate: '06/15/1979',
            sex: 'Female',
            homeAddress: 'Monte de Piedad Street',
            contactNumber: '099943',
            dateRegistered: 1633262275,
            timeIn: 1633262208,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 167993230675,
            firstName: 'Tim',
            lastName: 'Stahl',
            birthDate: '08/20/1970',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099944',
            dateRegistered: 1633262275,
            timeIn: 1633262198,
            timeOut: 1633262307,
            userType: 'Personel',
            gpsDevice: 'GPS-44',
          },

          {
            id: 148352781014,
            firstName: 'Mark',
            lastName: 'Ulrich',
            birthDate: '08/08/1973',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099945',
            dateRegistered: 1633262275,
            timeIn: 1633262261,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 199179913420,
            firstName: 'Fred',
            lastName: 'Vail',
            birthDate: '04/24/1975',
            sex: 'Male',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099946',
            dateRegistered: 1633262275,
            timeIn: 1633262248,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-46',
          },

          {
            id: 150709202954,
            firstName: 'Edward',
            lastName: 'Soukup',
            birthDate: '06/28/1965',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099947',
            dateRegistered: 1633262275,
            timeIn: 1633262238,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 971801586396,
            firstName: 'George',
            lastName: 'Ebner',
            birthDate: '05/23/1975',
            sex: 'Female',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099948',
            dateRegistered: 1633262275,
            timeIn: 1633262269,
            timeOut: 1633262342,
            userType: 'Personel',
            gpsDevice: 'GPS-48',
          },

          {
            id: 1617727776094,
            firstName: 'Adam',
            lastName: 'Davis',
            birthDate: '12/25/1989',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099949',
            dateRegistered: 1633262275,
            timeIn: 1633262205,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1434133779276,
            firstName: 'Steve',
            lastName: 'Jones',
            birthDate: '02/19/1986',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099950',
            dateRegistered: 1633262275,
            timeIn: 1633262234,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-50',
          },

          {
            id: 215491126791,
            firstName: 'Dan',
            lastName: 'Zeller',
            birthDate: '02/27/1979',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099951',
            dateRegistered: 1633262275,
            timeIn: 1633262244,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 255983613134,
            firstName: 'Adam',
            lastName: 'Hylan',
            birthDate: '04/24/1979',
            sex: 'Female',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099952',
            dateRegistered: 1633262275,
            timeIn: 1633262202,
            timeOut: 1633262330,
            userType: 'Personel',
            gpsDevice: 'GPS-52',
          },

          {
            id: 202390162096,
            firstName: 'Hank',
            lastName: 'Eastman',
            birthDate: '05/27/1999',
            sex: 'Female',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '099953',
            dateRegistered: 1633262275,
            timeIn: 1633262264,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 664802865120,
            firstName: 'George',
            lastName: 'Ingram',
            birthDate: '09/19/1989',
            sex: 'Female',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099954',
            dateRegistered: 1633262275,
            timeIn: 1633262208,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-54',
          },

          {
            id: 810432785276,
            firstName: 'Peter',
            lastName: 'Cast',
            birthDate: '09/12/1965',
            sex: 'Male',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099955',
            dateRegistered: 1633262275,
            timeIn: 1633262264,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1338186453891,
            firstName: 'Walter',
            lastName: 'Schwager',
            birthDate: '04/10/1998',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099956',
            dateRegistered: 1633262275,
            timeIn: 1633262262,
            timeOut: 1633262325,
            userType: 'Personel',
            gpsDevice: 'GPS-56',
          },

          {
            id: 608405524231,
            firstName: 'Aaron',
            lastName: 'Ferro',
            birthDate: '05/28/1999',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099957',
            dateRegistered: 1633262275,
            timeIn: 1633262233,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1350671997668,
            firstName: 'Thomas',
            lastName: 'Bauer',
            birthDate: '08/23/1998',
            sex: 'Female',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099958',
            dateRegistered: 1633262275,
            timeIn: 1633262253,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-58',
          },

          {
            id: 788623900255,
            firstName: 'Larry',
            lastName: 'Maki',
            birthDate: '08/11/1962',
            sex: 'Male',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099959',
            dateRegistered: 1633262275,
            timeIn: 1633262228,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1015246596905,
            firstName: 'David',
            lastName: 'Johnson',
            birthDate: '10/17/1978',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099960',
            dateRegistered: 1633262275,
            timeIn: 1633262230,
            timeOut: 1633262313,
            userType: 'Personel',
            gpsDevice: 'GPS-60',
          },

          {
            id: 770674582449,
            firstName: 'Aaron',
            lastName: 'Sandstrom',
            birthDate: '11/24/1992',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099961',
            dateRegistered: 1633262275,
            timeIn: 1633262206,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1563305982398,
            firstName: 'Ben',
            lastName: 'Miller',
            birthDate: '06/16/1960',
            sex: 'Female',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099962',
            dateRegistered: 1633262275,
            timeIn: 1633262242,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-62',
          },

          {
            id: 1198285846153,
            firstName: 'David',
            lastName: 'Yocum',
            birthDate: '04/06/1997',
            sex: 'Male',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099963',
            dateRegistered: 1633262275,
            timeIn: 1633262192,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1308750555363,
            firstName: 'Adam',
            lastName: 'Roberts',
            birthDate: '06/25/2002',
            sex: 'Female',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099964',
            dateRegistered: 1633262275,
            timeIn: 1633262208,
            timeOut: 1633262282,
            userType: 'Personel',
            gpsDevice: 'GPS-64',
          },

          {
            id: 432593791665,
            firstName: 'David',
            lastName: 'Napier',
            birthDate: '09/09/2002',
            sex: 'Female',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099965',
            dateRegistered: 1633262275,
            timeIn: 1633262235,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 766536920813,
            firstName: 'Ike',
            lastName: 'Jones',
            birthDate: '07/21/1996',
            sex: 'Female',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099966',
            dateRegistered: 1633262275,
            timeIn: 1633262216,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-66',
          },

          {
            id: 1154062781427,
            firstName: 'Matthew',
            lastName: 'Van Zandt',
            birthDate: '11/09/1990',
            sex: 'Male',
            homeAddress: 'Monte de Piedad Street',
            contactNumber: '099967',
            dateRegistered: 1633262275,
            timeIn: 1633262232,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1432457391404,
            firstName: 'Roger',
            lastName: 'Schiebel',
            birthDate: '06/27/1980',
            sex: 'Male',
            homeAddress: 'Carlos Palanca Street',
            contactNumber: '099968',
            dateRegistered: 1633262275,
            timeIn: 1633262192,
            timeOut: 1633262277,
            userType: 'Personel',
            gpsDevice: 'GPS-68',
          },

          {
            id: 185348620548,
            firstName: 'Ben',
            lastName: 'Nugent',
            birthDate: '03/05/1979',
            sex: 'Male',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099969',
            dateRegistered: 1633262275,
            timeIn: 1633262270,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 851591372739,
            firstName: 'Joe',
            lastName: 'Frick',
            birthDate: '10/14/1969',
            sex: 'Female',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099970',
            dateRegistered: 1633262275,
            timeIn: 1633262231,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-70',
          },

          {
            id: 760722051744,
            firstName: 'Thomas',
            lastName: 'Upson',
            birthDate: '01/26/1965',
            sex: 'Female',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099971',
            dateRegistered: 1633262275,
            timeIn: 1633262226,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 152290052128,
            firstName: 'Ike',
            lastName: 'Ashwoon',
            birthDate: '02/24/1978',
            sex: 'Female',
            homeAddress: 'Monte de Piedad Street',
            contactNumber: '099972',
            dateRegistered: 1633262275,
            timeIn: 1633262192,
            timeOut: 1633262327,
            userType: 'Personel',
            gpsDevice: 'GPS-72',
          },

          {
            id: 1106670808317,
            firstName: 'Aaron',
            lastName: 'Keller',
            birthDate: '09/15/1969',
            sex: 'Male',
            homeAddress: 'Monte de Piedad Street',
            contactNumber: '099973',
            dateRegistered: 1633262275,
            timeIn: 1633262265,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 494728822842,
            firstName: 'Steve',
            lastName: 'Keller',
            birthDate: '07/21/1983',
            sex: 'Male',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099974',
            dateRegistered: 1633262275,
            timeIn: 1633262263,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-74',
          },

          {
            id: 582604082017,
            firstName: 'David',
            lastName: 'Lawless',
            birthDate: '09/22/1996',
            sex: 'Female',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099975',
            dateRegistered: 1633262275,
            timeIn: 1633262193,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 507170177320,
            firstName: 'Ike',
            lastName: 'Soukup',
            birthDate: '12/27/1996',
            sex: 'Female',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099976',
            dateRegistered: 1633262275,
            timeIn: 1633262198,
            timeOut: 1633262290,
            userType: 'Personel',
            gpsDevice: 'GPS-76',
          },

          {
            id: 776121057406,
            firstName: 'Paul',
            lastName: 'Nelson',
            birthDate: '04/19/1983',
            sex: 'Male',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099977',
            dateRegistered: 1633262275,
            timeIn: 1633262268,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 571107971329,
            firstName: 'Roger',
            lastName: 'Stahl',
            birthDate: '05/23/2001',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099978',
            dateRegistered: 1633262275,
            timeIn: 1633262203,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-78',
          },

          {
            id: 906473308286,
            firstName: 'Aaron',
            lastName: 'Schiebel',
            birthDate: '02/15/1986',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099979',
            dateRegistered: 1633262275,
            timeIn: 1633262199,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1274905653006,
            firstName: 'Mark',
            lastName: 'Duffman',
            birthDate: '08/10/1985',
            sex: 'Male',
            homeAddress: 'Gil Fernando Avenue 0',
            contactNumber: '099980',
            dateRegistered: 1633262275,
            timeIn: 1633262255,
            timeOut: 1633262332,
            userType: 'Personel',
            gpsDevice: 'GPS-80',
          },

          {
            id: 778368657104,
            firstName: 'Aaron',
            lastName: 'Ostrander',
            birthDate: '01/20/1976',
            sex: 'Female',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099981',
            dateRegistered: 1633262275,
            timeIn: 1633262222,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 321801706762,
            firstName: 'Adam',
            lastName: 'Zeller',
            birthDate: '12/07/1966',
            sex: 'Female',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099982',
            dateRegistered: 1633262275,
            timeIn: 1633262266,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-82',
          },

          {
            id: 1485540690511,
            firstName: 'Adam',
            lastName: 'Norquist',
            birthDate: '01/11/1994',
            sex: 'Female',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099983',
            dateRegistered: 1633262275,
            timeIn: 1633262225,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1453759749454,
            firstName: 'Peter',
            lastName: 'Valente',
            birthDate: '10/13/1978',
            sex: 'Male',
            homeAddress: 'Monte de Piedad Street',
            contactNumber: '099984',
            dateRegistered: 1633262275,
            timeIn: 1633262238,
            timeOut: 1633262352,
            userType: 'Personel',
            gpsDevice: 'GPS-84',
          },

          {
            id: 215155605954,
            firstName: 'Frank',
            lastName: 'Reyes',
            birthDate: '12/04/1967',
            sex: 'Male',
            homeAddress: 'J. Escrivà Drive',
            contactNumber: '099985',
            dateRegistered: 1633262275,
            timeIn: 1633262231,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 254732386925,
            firstName: 'Steve',
            lastName: 'Severson',
            birthDate: '09/09/1987',
            sex: 'Male',
            homeAddress: 'N. Domingo Street',
            contactNumber: '099986',
            dateRegistered: 1633262275,
            timeIn: 1633262242,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-86',
          },

          {
            id: 1229500816909,
            firstName: 'Ike',
            lastName: 'Leisinger',
            birthDate: '05/01/1960',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099987',
            dateRegistered: 1633262275,
            timeIn: 1633262259,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 183081613549,
            firstName: 'Matthew',
            lastName: 'Moody',
            birthDate: '03/09/1965',
            sex: 'Female',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099988',
            dateRegistered: 1633262275,
            timeIn: 1633262203,
            timeOut: 1633262354,
            userType: 'Personel',
            gpsDevice: 'GPS-88',
          },

          {
            id: 1067874514040,
            firstName: 'Joe',
            lastName: 'Hoffman',
            birthDate: '12/06/1992',
            sex: 'Male',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099989',
            dateRegistered: 1633262275,
            timeIn: 1633262193,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1365604822094,
            firstName: 'Ben',
            lastName: 'Jenson',
            birthDate: '12/20/1977',
            sex: 'Male',
            homeAddress: 'Mayor Ignacio Santos Diaz Street',
            contactNumber: '099990',
            dateRegistered: 1633262275,
            timeIn: 1633262238,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-90',
          },

          {
            id: 628391396870,
            firstName: 'Roger',
            lastName: 'Caswell',
            birthDate: '10/24/1963',
            sex: 'Female',
            homeAddress: 'F. Antonio 0',
            contactNumber: '099991',
            dateRegistered: 1633262275,
            timeIn: 1633262269,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1575015596673,
            firstName: 'Joe',
            lastName: 'Eastman',
            birthDate: '07/10/1972',
            sex: 'Male',
            homeAddress: 'N. Domingo Street',
            contactNumber: '099992',
            dateRegistered: 1633262275,
            timeIn: 1633262271,
            timeOut: 1633262324,
            userType: 'Personel',
            gpsDevice: 'GPS-92',
          },

          {
            id: 1421471811336,
            firstName: 'Steve',
            lastName: 'Hancock',
            birthDate: '11/01/1984',
            sex: 'Male',
            homeAddress: 'N. Domingo Street',
            contactNumber: '099993',
            dateRegistered: 1633262275,
            timeIn: 1633262242,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 108362438679,
            firstName: 'John',
            lastName: 'Schuster',
            birthDate: '01/26/1970',
            sex: 'Female',
            homeAddress: 'P. Bernardo Street',
            contactNumber: '099994',
            dateRegistered: 1633262275,
            timeIn: 1633262267,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-94',
          },

          {
            id: 1352078878043,
            firstName: 'Monte',
            lastName: 'Roberts',
            birthDate: '06/12/1985',
            sex: 'Male',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099995',
            dateRegistered: 1633262275,
            timeIn: 1633262193,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 788496989741,
            firstName: 'Steve',
            lastName: 'Quizoz',
            birthDate: '06/22/1989',
            sex: 'Male',
            homeAddress: 'L. P. Leviste Street',
            contactNumber: '099996',
            dateRegistered: 1633262275,
            timeIn: 1633262253,
            timeOut: 1633262309,
            userType: 'Personel',
            gpsDevice: 'GPS-96',
          },

          {
            id: 1453238842627,
            firstName: 'Fred',
            lastName: 'Soulis',
            birthDate: '04/30/1999',
            sex: 'Female',
            homeAddress: 'Macario Asistio, Sr. Avenue',
            contactNumber: '099997',
            dateRegistered: 1633262275,
            timeIn: 1633262230,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },

          {
            id: 1288469778411,
            firstName: 'Peter',
            lastName: 'Vader',
            birthDate: '12/05/1980',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099998',
            dateRegistered: 1633262275,
            timeIn: 1633262210,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: 'GPS-98',
          },

          {
            id: 1277974772347,
            firstName: 'Thomas',
            lastName: 'Ramachandran',
            birthDate: '08/23/2000',
            sex: 'Male',
            homeAddress: 'Alfonso XIII',
            contactNumber: '099999',
            dateRegistered: 1633262275,
            timeIn: 1633262201,
            timeOut: null,
            userType: 'Visitor',
            gpsDevice: null,
          },
        ])
      );
    }

    if (!JSON.parse(localStorage.getItem('gpsDevices'))) {
      // Set static dummy data of gpsDevices
      localStorage.setItem(
        'gpsDevices',
        JSON.stringify([
          {
            id: 'GPS-0',
            isAssigned: true,
          },
          {
            id: 'GPS-1',
            isAssigned: false,
          },
          {
            id: 'GPS-2',
            isAssigned: true,
          },
          {
            id: 'GPS-3',
            isAssigned: false,
          },
          {
            id: 'GPS-4',
            isAssigned: true,
          },
          {
            id: 'GPS-5',
            isAssigned: false,
          },
          {
            id: 'GPS-6',
            isAssigned: true,
          },
          {
            id: 'GPS-7',
            isAssigned: false,
          },
          {
            id: 'GPS-8',
            isAssigned: true,
          },
          {
            id: 'GPS-9',
            isAssigned: false,
          },
          {
            id: 'GPS-10',
            isAssigned: true,
          },
          {
            id: 'GPS-11',
            isAssigned: false,
          },
          {
            id: 'GPS-12',
            isAssigned: true,
          },
          {
            id: 'GPS-13',
            isAssigned: false,
          },
          {
            id: 'GPS-14',
            isAssigned: true,
          },
          {
            id: 'GPS-15',
            isAssigned: false,
          },
          {
            id: 'GPS-16',
            isAssigned: true,
          },
          {
            id: 'GPS-17',
            isAssigned: false,
          },
          {
            id: 'GPS-18',
            isAssigned: true,
          },
          {
            id: 'GPS-19',
            isAssigned: false,
          },
          {
            id: 'GPS-20',
            isAssigned: true,
          },
          {
            id: 'GPS-21',
            isAssigned: false,
          },
          {
            id: 'GPS-22',
            isAssigned: true,
          },
          {
            id: 'GPS-23',
            isAssigned: false,
          },
          {
            id: 'GPS-24',
            isAssigned: true,
          },
          {
            id: 'GPS-25',
            isAssigned: false,
          },
          {
            id: 'GPS-26',
            isAssigned: true,
          },
          {
            id: 'GPS-27',
            isAssigned: false,
          },
          {
            id: 'GPS-28',
            isAssigned: true,
          },
          {
            id: 'GPS-29',
            isAssigned: false,
          },
          {
            id: 'GPS-30',
            isAssigned: true,
          },
          {
            id: 'GPS-31',
            isAssigned: false,
          },
          {
            id: 'GPS-32',
            isAssigned: true,
          },
          {
            id: 'GPS-33',
            isAssigned: false,
          },
          {
            id: 'GPS-34',
            isAssigned: true,
          },
          {
            id: 'GPS-35',
            isAssigned: false,
          },
          {
            id: 'GPS-36',
            isAssigned: true,
          },
          {
            id: 'GPS-37',
            isAssigned: false,
          },
          {
            id: 'GPS-38',
            isAssigned: true,
          },
          {
            id: 'GPS-39',
            isAssigned: false,
          },
          {
            id: 'GPS-40',
            isAssigned: true,
          },
          {
            id: 'GPS-41',
            isAssigned: false,
          },
          {
            id: 'GPS-42',
            isAssigned: true,
          },
          {
            id: 'GPS-43',
            isAssigned: false,
          },
          {
            id: 'GPS-44',
            isAssigned: true,
          },
          {
            id: 'GPS-45',
            isAssigned: false,
          },
          {
            id: 'GPS-46',
            isAssigned: true,
          },
          {
            id: 'GPS-47',
            isAssigned: false,
          },
          {
            id: 'GPS-48',
            isAssigned: true,
          },
          {
            id: 'GPS-49',
            isAssigned: false,
          },
          {
            id: 'GPS-50',
            isAssigned: true,
          },
          {
            id: 'GPS-51',
            isAssigned: false,
          },
          {
            id: 'GPS-52',
            isAssigned: true,
          },
          {
            id: 'GPS-53',
            isAssigned: false,
          },
          {
            id: 'GPS-54',
            isAssigned: true,
          },
          {
            id: 'GPS-55',
            isAssigned: false,
          },
          {
            id: 'GPS-56',
            isAssigned: true,
          },
          {
            id: 'GPS-57',
            isAssigned: false,
          },
          {
            id: 'GPS-58',
            isAssigned: true,
          },
          {
            id: 'GPS-59',
            isAssigned: false,
          },
          {
            id: 'GPS-60',
            isAssigned: true,
          },
          {
            id: 'GPS-61',
            isAssigned: false,
          },
          {
            id: 'GPS-62',
            isAssigned: true,
          },
          {
            id: 'GPS-63',
            isAssigned: false,
          },
          {
            id: 'GPS-64',
            isAssigned: true,
          },
          {
            id: 'GPS-65',
            isAssigned: false,
          },
          {
            id: 'GPS-66',
            isAssigned: true,
          },
          {
            id: 'GPS-67',
            isAssigned: false,
          },
          {
            id: 'GPS-68',
            isAssigned: true,
          },
          {
            id: 'GPS-69',
            isAssigned: false,
          },
          {
            id: 'GPS-70',
            isAssigned: true,
          },
          {
            id: 'GPS-71',
            isAssigned: false,
          },
          {
            id: 'GPS-72',
            isAssigned: true,
          },
          {
            id: 'GPS-73',
            isAssigned: false,
          },
          {
            id: 'GPS-74',
            isAssigned: true,
          },
          {
            id: 'GPS-75',
            isAssigned: false,
          },
          {
            id: 'GPS-76',
            isAssigned: true,
          },
          {
            id: 'GPS-77',
            isAssigned: false,
          },
          {
            id: 'GPS-78',
            isAssigned: true,
          },
          {
            id: 'GPS-79',
            isAssigned: false,
          },
          {
            id: 'GPS-80',
            isAssigned: true,
          },
          {
            id: 'GPS-81',
            isAssigned: false,
          },
          {
            id: 'GPS-82',
            isAssigned: true,
          },
          {
            id: 'GPS-83',
            isAssigned: false,
          },
          {
            id: 'GPS-84',
            isAssigned: true,
          },
          {
            id: 'GPS-85',
            isAssigned: false,
          },
          {
            id: 'GPS-86',
            isAssigned: true,
          },
          {
            id: 'GPS-87',
            isAssigned: false,
          },
          {
            id: 'GPS-88',
            isAssigned: true,
          },
          {
            id: 'GPS-89',
            isAssigned: false,
          },
          {
            id: 'GPS-90',
            isAssigned: true,
          },
          {
            id: 'GPS-91',
            isAssigned: false,
          },
          {
            id: 'GPS-92',
            isAssigned: true,
          },
          {
            id: 'GPS-93',
            isAssigned: false,
          },
          {
            id: 'GPS-94',
            isAssigned: true,
          },
          {
            id: 'GPS-95',
            isAssigned: false,
          },
          {
            id: 'GPS-96',
            isAssigned: true,
          },
          {
            id: 'GPS-97',
            isAssigned: false,
          },
          {
            id: 'GPS-98',
            isAssigned: true,
          },
          {
            id: 'GPS-99',
            isAssigned: false,
          },
        ])
      );
    }
  }, []);

  return (
    <BrowserRouter basename="/">
      <React.Suspense fallback={<div>Loading...</div>}>
        <Switch>
          <Route
            path="/registration"
            name="Registration"
            render={(props) => <Registration {...props} />}
          />

          <Route
            path="/map"
            name="Map"
            render={(props) => <Map {...props} />}
          />

          <Route
            path="/users"
            name="Users"
            render={(props) => <Users {...props} />}
          />

          <Redirect to="/page-not-found" />
        </Switch>
      </React.Suspense>
    </BrowserRouter>
  );
};

export default App;
